FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/web/package.json apps/web/package.json

RUN npm install

COPY . .

RUN npm run build --workspace=@nnit-studio/web

EXPOSE 3000

CMD ["sh","-c","npm run start --workspace=@nnit-studio/web"]
